### ISSUE TITLE
onScroll event swallowed after upgrade to preact 8.x

### ISSUE THREAD

**Issue by pascalopitz** [developit/preact-virtual-list#6]
The onScroll on my top level element does not get triggered anymore after upgrade to 8.x.

```
<div id="music-sources-container" onScroll={this._onScroll.bind(this)}>
	{headlineNodes}
	<ul id="browser-container">
	    <VirtualList
	        rowHeight={50} sync={true} class="scrollcontainer"
		data={[actionNodes].concat(listItemNodes)}
		renderRow={this._renderRow.bind(this)}
		>
	     </VirtualList>
    </ul>
</div>
```

**Comment by pascalopitz** [comment]
Has this to do with "Removed Event Recycling"?

https://gist.github.com/developit/89e0e6decb8fb5eb00def024b6fb7bd7

**Comment by pascalopitz** [comment]
Ah, I figured it out. using onScrollCapture instead. Details see:

https://github.com/developit/preact/commit/727f0360c72a933eb46f16db73e7ef9217302d1d#diff-4935bb00e75b7854383877cbfd9d770f

**Comment by developit** [comment]
Ah, thanks for digging in and finding that.  Hopefully people will find this issue if they google a similar problem!
